# Frontend build stage
FROM node:22-alpine AS web-builder

WORKDIR /usr/src/bilistream/web
COPY web/package.json web/pnpm-lock.yaml ./
RUN corepack enable && pnpm install --frozen-lockfile
COPY web ./
RUN pnpm run build

# Rust build stage
FROM rust:alpine AS builder

RUN apk add --no-cache \
    musl-dev \
    pkgconfig

WORKDIR /usr/src/bilistream

COPY . .
COPY --from=web-builder /usr/src/bilistream/web/out ./web/out

RUN cargo build --release && \
    strip target/release/bilistream && \
    chmod +x target/release/bilistream

# Final runtime stage
FROM ghcr.io/jim60105/yt-dlp:latest

ENTRYPOINT []

WORKDIR /app

COPY --from=builder /usr/src/bilistream/target/release/bilistream /app/
COPY --from=builder /usr/src/bilistream/web/out /app/web/out

CMD ["/app/bilistream"]
