services:
  bilistream:
    image: ghcr.io/limitcool/bilistream:v0.2.0
    container_name: bilistream
    ports:
      - "9090:9090"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./cookies.txt:/app/cookies.txt:ro
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    # 如需代理，可取消下方注释并按实际地址修改
    # network_mode: "host"
    # environment:
    #   - http_proxy=http://host.docker.internal:7890
    #   - https_proxy=http://host.docker.internal:7890
